services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres

  app:
    build: .
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:pass123@db:5432/postgres
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:pass123@db:5432/postgres
    depends_on:
      - db
